### ISSUE TITLE
File.getCanonicalPath() throws IOException on Windows if File was constructed from URI string

### ISSUE THREAD

**Issue by mmajis** [searls/jasmine-maven-plugin#26]
I'm getting an IOException trying to run anything newer than 1.0.2-beta2 on Windows XP.

```
[INFO] The jasmine-maven-plugin encountered an exception:
java.io.IOException: The filename, directory name, or volume label syntax is incorrect
        at java.io.WinNTFileSystem.canonicalize0(Native Method)
        at java.io.Win32FileSystem.canonicalize(Win32FileSystem.java:396)
        at java.io.File.getCanonicalPath(File.java:559)
        at com.github.searls.jasmine.io.RelativizesFilePaths.relativize(RelativizesFilePaths.java:15)
        at com.github.searls.jasmine.io.scripts.RelativizesASetOfScripts.relativize(RelativizesASetOfScripts.java:17)
        at com.github.searls.jasmine.CreatesManualRunner.scriptsForRunner(CreatesManualRunner.java:43)
        at com.github.searls.jasmine.CreatesManualRunner.create(CreatesManualRunner.java:34)
        at com.github.searls.jasmine.GenerateManualRunnerMojo.run(GenerateManualRunnerMojo.java:15)
        at com.github.searls.jasmine.AbstractJasmineMojo.execute(AbstractJasmineMojo.java:193)
        ...
```

It seems like this is due to using ConvertsFileToUriString.convert(file) for script files and later calling the equivalent of new File(theURIString).getCanonicalPath() in RelativizesFilePaths.relativize(). If the File is constructed using a URI object, however, things seem to work: new File(new URI(theURIString)).getCanonicalPath().

Keep up the good work! :)

**Comment by mufaro23** [comment]
Hi Searls, am having the same problem on android studio can you please help me. Here is the error:

The device is not ready
java.io.IOException: The device is not ready
	at java.io.WinNTFileSystem.canonicalize0(Native Method)
	at java.io.WinNTFileSystem.canonicalize(WinNTFileSystem.java:404)
	at java.io.File.getCanonicalPath(File.java:618)
	at java.io.File.getCanonicalFile(File.java:643)
	at com.android.tools.idea.stats.RunStatsService.notifyDeploySplitApkStarted(RunStatsService.kt:98)
	at com.android.tools.idea.run.tasks.SplitApkDeployTask.perform(SplitApkDeployTask.java:80)
	at com.android.tools.idea.run.LaunchTaskRunner.run(LaunchTaskRunner.java:121)
	at com.intellij.openapi.progress.impl.CoreProgressManager$TaskRunnable.run(CoreProgressManager.java:750)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$1(CoreProgressManager.java:157)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:580)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:525)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:85)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:144)
	at com.intellij.openapi.progress.impl.CoreProgressManager$4.run(CoreProgressManager.java:395)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.run(ApplicationImpl.java:305)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

**Comment by Amiya-873** [comment]
> Alright, I think I figured out what's happening. The class [ResolvesCompleteListOfScriptLocations.java](https://github.com/searls/jasmine-maven-plugin/blob/master/src/main/java/com/github/searls/jasmine/io/scripts/ResolvesCompleteListOfScriptLocations.java) constructs a bunch of file URIs as strings. in Windows, this will result in names like `file:/c:/...` which the `File#getCanonicalPath()` method (understandably) doesn't like.
> 
> I'll try to get this fixed ASAP since it'll probably be broken for all Windows users.

How to fix this kind of issue?
