### ISSUE TITLE
'jasmine:bdd' runs tests successfully but 'jasmine:test' fails 

### ISSUE THREAD

**Issue by lwiechec** [searls/jasmine-maven-plugin#286]
Hi,

I am trying to use Jasmine plugin in testing our [ExtJS](http://sencha.com/extjs) app and I manage to get the 'jasmine:bdd' working (ie. tests are run and pass) but running 'jasmine:test' fails with following message:

```
[INFO] --- jasmine-maven-plugin:2.0:test (default-cli) @ viewer ---
[INFO] jetty-8.1.14.v20131031
[INFO] Started SelectChannelConnector@0.0.0.0:40252
[INFO] Executing Jasmine Specs
Oct 09, 2015 5:17:28 PM org.openqa.selenium.phantomjs.PhantomJSDriverService <init>
INFO: executable: /usr/bin/phantomjs
Oct 09, 2015 5:17:28 PM org.openqa.selenium.phantomjs.PhantomJSDriverService <init>
INFO: port: 3285
Oct 09, 2015 5:17:28 PM org.openqa.selenium.phantomjs.PhantomJSDriverService <init>
INFO: arguments: [--proxy-type=http, --proxy=proxy:8088, --disk-cache=true, --max-disk-cache-size=256, --webdriver=3285, --webdriver-logfile=/home/luke/work/projects/CCIF-ng/phantomjsdriver.log]
Oct 09, 2015 5:17:28 PM org.openqa.selenium.phantomjs.PhantomJSDriverService <init>
INFO: environment: {}
PhantomJS is launching GhostDriver...
[INFO  - 2015-10-09T15:17:28.863Z] GhostDriver - Main - running on port 3285
[INFO  - 2015-10-09T15:17:29.381Z] Session [db0c5110-6e98-11e5-9eaf-db192ff5df23] - CONSTRUCTOR - Desired Capabilities: {"proxy":{"httpProxy":"proxy:8088"},"phantomjs.binary.path":"/usr/bin/phantomjs","browserName":"phantomjs","javascriptEnabled":true,"phantomjs.cli.args":["--disk-cache=true","--max-disk-cache-size=256"],"version":"","platform":"ANY"}
[INFO  - 2015-10-09T15:17:29.381Z] Session [db0c5110-6e98-11e5-9eaf-db192ff5df23] - CONSTRUCTOR - Negotiated Capabilities: {"browserName":"phantomjs","version":"1.9.0","driverName":"ghostdriver","driverVersion":"1.0.3","platform":"linux-unknown-64bit","javascriptEnabled":true,"takesScreenshot":true,"handlesAlerts":false,"databaseEnabled":false,"locationContextEnabled":false,"applicationCacheEnabled":false,"browserConnectionEnabled":false,"cssSelectorsEnabled":true,"webStorageEnabled":false,"rotatable":false,"acceptSslCerts":false,"nativeEvents":true,"proxy":{"httpProxy":"proxy:8088"}}
[INFO  - 2015-10-09T15:17:29.381Z] SessionManagerReqHand - _postNewSessionCommand - New Session Created: db0c5110-6e98-11e5-9eaf-db192ff5df23
[INFO  - 2015-10-09T15:17:32.825Z] ShutdownReqHand - _handle - About to shutdown
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 6.935 s
[INFO] Finished at: 2015-10-09T17:17:33+02:00
[INFO] Final Memory: 43M/403M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal com.github.searls:jasmine-maven-plugin:2.0:test (default-cli) on project viewer: The jasmine-maven-plugin encountered an exception:
[ERROR] java.lang.RuntimeException: org.openqa.selenium.WebDriverException: Error Message => 'URL 'http://localhost:40252' didn't load. Error: 'TypeError: 'undefined' is not an object (evaluating 'assets.length')''
[ERROR] caused by Request => {"headers":{"Accept-Encoding":"gzip,deflate","Connection":"Keep-Alive","Content-Length":"32","Content-Type":"application/json; charset=utf-8","Host":"localhost:3285","User-Agent":"Apache-HttpClient/4.3.6 (java 1.5)"},"httpVersion":"1.1","method":"POST","post":"{\"url\":\"http://localhost:40252\"}","url":"/url","urlParsed":{"anchor":"","query":"","file":"url","directory":"/","path":"/url","relative":"/url","port":"","host":"","password":"","user":"","userInfo":"","authority":"","protocol":"","source":"/url","queryKey":{},"chunks":["url"]},"urlOriginal":"/session/db0c5110-6e98-11e5-9eaf-db192ff5df23/url"}
[ERROR] Command duration or timeout: 3.35 seconds
[ERROR] Build info: version: '2.45.0', revision: '5017cb8e7ca8e37638dc3091b2440b90a1d8686f', time: '2015-02-27 09:10:26'
[ERROR] System info: host: 'luke-new-laptop', ip: '127.0.1.1', os.name: 'Linux', os.arch: 'amd64', os.version: '3.13.0-63-generic', java.version: '1.8.0_60'
[ERROR] Driver info: org.openqa.selenium.phantomjs.PhantomJSDriver
[ERROR] Capabilities [{applicationCacheEnabled=false, rotatable=false, handlesAlerts=false, databaseEnabled=false, version=1.9.0, platform=LINUX, browserConnectionEnabled=false, proxy={httpProxy=proxy:8088}, nativeEvents=true, acceptSslCerts=false, driverVersion=1.0.3, locationContextEnabled=false, webStorageEnabled=false, browserName=phantomjs, takesScreenshot=true, driverName=ghostdriver, javascriptEnabled=true, cssSelectorsEnabled=true}]
[ERROR] Session ID: db0c5110-6e98-11e5-9eaf-db192ff5df23
[ERROR] at com.github.searls.jasmine.runner.SpecRunnerExecutor.execute(SpecRunnerExecutor.java:53)
[ERROR] at com.github.searls.jasmine.mojo.TestMojo.executeSpecs(TestMojo.java:236)
[ERROR] at com.github.searls.jasmine.mojo.TestMojo.run(TestMojo.java:204)
[ERROR] at com.github.searls.jasmine.mojo.AbstractJasmineMojo.execute(AbstractJasmineMojo.java:385)
[ERROR] at com.github.searls.jasmine.mojo.TestMojo.execute(TestMojo.java:191)
[ERROR] at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:132)
[ERROR] at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
[ERROR] at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
[ERROR] at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
[ERROR] at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
[ERROR] at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
[ERROR] at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
[ERROR] at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:120)
[ERROR] at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:355)
[ERROR] at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:155)
[ERROR] at org.apache.maven.cli.MavenCli.execute(MavenCli.java:584)
[ERROR] at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:216)
[ERROR] at org.apache.maven.cli.MavenCli.main(MavenCli.java:160)
[ERROR] at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[ERROR] at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[ERROR] at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[ERROR] at java.lang.reflect.Method.invoke(Method.java:497)
[ERROR] at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
[ERROR] at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
[ERROR] at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
[ERROR] at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
[ERROR] Caused by: org.openqa.selenium.WebDriverException: Error Message => 'URL 'http://localhost:40252' didn't load. Error: 'TypeError: 'undefined' is not an object (evaluating 'assets.length')''
[ERROR] caused by Request => {"headers":{"Accept-Encoding":"gzip,deflate","Connection":"Keep-Alive","Content-Length":"32","Content-Type":"application/json; charset=utf-8","Host":"localhost:3285","User-Agent":"Apache-HttpClient/4.3.6 (java 1.5)"},"httpVersion":"1.1","method":"POST","post":"{\"url\":\"http://localhost:40252\"}","url":"/url","urlParsed":{"anchor":"","query":"","file":"url","directory":"/","path":"/url","relative":"/url","port":"","host":"","password":"","user":"","userInfo":"","authority":"","protocol":"","source":"/url","queryKey":{},"chunks":["url"]},"urlOriginal":"/session/db0c5110-6e98-11e5-9eaf-db192ff5df23/url"}
[ERROR] Command duration or timeout: 3.35 seconds
[ERROR] Build info: version: '2.45.0', revision: '5017cb8e7ca8e37638dc3091b2440b90a1d8686f', time: '2015-02-27 09:10:26'
[ERROR] System info: host: 'luke-new-laptop', ip: '127.0.1.1', os.name: 'Linux', os.arch: 'amd64', os.version: '3.13.0-63-generic', java.version: '1.8.0_60'
[ERROR] Driver info: org.openqa.selenium.phantomjs.PhantomJSDriver
[ERROR] Capabilities [{applicationCacheEnabled=false, rotatable=false, handlesAlerts=false, databaseEnabled=false, version=1.9.0, platform=LINUX, browserConnectionEnabled=false, proxy={httpProxy=proxy:8088}, nativeEvents=true, acceptSslCerts=false, driverVersion=1.0.3, locationContextEnabled=false, webStorageEnabled=false, browserName=phantomjs, takesScreenshot=true, driverName=ghostdriver, javascriptEnabled=true, cssSelectorsEnabled=true}]
[ERROR] Session ID: db0c5110-6e98-11e5-9eaf-db192ff5df23
[ERROR] at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[ERROR] at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
[ERROR] at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[ERROR] at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
[ERROR] at org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:204)
[ERROR] at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:156)
[ERROR] at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:599)
[ERROR] at org.openqa.selenium.remote.RemoteWebDriver.get(RemoteWebDriver.java:304)
[ERROR] at com.github.searls.jasmine.runner.SpecRunnerExecutor.execute(SpecRunnerExecutor.java:42)
[ERROR] ... 25 more
[ERROR] Caused by: org.openqa.selenium.remote.ScreenshotException: Screen shot has been taken
[ERROR] Build info: version: '2.45.0', revision: '5017cb8e7ca8e37638dc3091b2440b90a1d8686f', time: '2015-02-27 09:10:26'
[ERROR] System info: host: 'luke-new-laptop', ip: '127.0.1.1', os.name: 'Linux', os.arch: 'amd64', os.version: '3.13.0-63-generic', java.version: '1.8.0_60'
[ERROR] Driver info: driver.version: RemoteWebDriver
[ERROR] at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:136)
[ERROR] ... 28 more
[ERROR] Caused by: org.openqa.selenium.WebDriverException: Error Message => 'URL 'http://localhost:40252' didn't load. Error: 'TypeError: 'undefined' is not an object (evaluating 'assets.length')''
[ERROR] caused by Request => {"headers":{"Accept-Encoding":"gzip,deflate","Connection":"Keep-Alive","Content-Length":"32","Content-Type":"application/json; charset=utf-8","Host":"localhost:3285","User-Agent":"Apache-HttpClient/4.3.6 (java 1.5)"},"httpVersion":"1.1","method":"POST","post":"{\"url\":\"http://localhost:40252\"}","url":"/url","urlParsed":{"anchor":"","query":"","file":"url","directory":"/","path":"/url","relative":"/url","port":"","host":"","password":"","user":"","userInfo":"","authority":"","protocol":"","source":"/url","queryKey":{},"chunks":["url"]},"urlOriginal":"/session/db0c5110-6e98-11e5-9eaf-db192ff5df23/url"}
[ERROR] Build info: version: '2.45.0', revision: '5017cb8e7ca8e37638dc3091b2440b90a1d8686f', time: '2015-02-27 09:10:26'
[ERROR] System info: host: 'luke-new-laptop', ip: '127.0.1.1', os.name: 'Linux', os.arch: 'amd64', os.version: '3.13.0-63-generic', java.version: '1.8.0_60'
[ERROR] Driver info: driver.version: unknown

```

any hint would be appreciated!

**Comment by lwiechec** [comment]
sorry, my bad: the tests were failing because of misconfiguration. My apologies.
