### ISSUE TITLE
The path to the driver executable must be set by the phantomjs.binary.path capability/system property/PATH variable

### ISSUE THREAD

**Issue by zhengchunxi** [searls/jasmine-maven-plugin#312]
**I use maven and  jasmine to test javascript,when run maven test:**
```
[ERROR] Failed to execute goal com.github.searls:jasmine-maven-plugin:2.2:test (default) on project JavascriptUT: The jasmine-maven-plugin encountered an exception:
[ERROR] java.lang.IllegalStateException: The path to the driver executable must be set by the phantomjs.binary.path capability/system property/PATH variable; for more information, see https://github.com/ariya/phantomjs/wiki. The latest version can be downloaded from http://phantomjs.org/download.html
[ERROR] at com.google.common.base.Preconditions.checkState(Preconditions.java:199)
[ERROR] at org.openqa.selenium.phantomjs.PhantomJSDriverService.findPhantomJS(PhantomJSDriverService.java:236)
[ERROR] at org.openqa.selenium.phantomjs.PhantomJSDriverService.createDefaultService(PhantomJSDriverService.java:181)
[ERROR] at org.openqa.selenium.phantomjs.PhantomJSDriver.<init>(PhantomJSDriver.java:104)
[ERROR] at com.github.searls.jasmine.driver.WebDriverFactory.createPhantomJsWebDriver(WebDriverFactory.java:149)
[ERROR] at com.github.searls.jasmine.driver.WebDriverFactory.createWebDriver(WebDriverFactory.java:68)
[ERROR] at com.github.searls.jasmine.mojo.TestMojo.createDriver(TestMojo.java:258)
[ERROR] at com.github.searls.jasmine.mojo.TestMojo.executeSpecs(TestMojo.java:228)
```
**here is my pom.xml**
```
<build>
		<plugins>
			<plugin>
				<groupId>com.github.searls</groupId>
				<artifactId>jasmine-maven-plugin</artifactId>
				<version>2.2</version>
				<executions>
					<execution>
						<goals><goal>test</goal></goals>
					</execution>
				</executions>
			</plugin>
		</plugins>
	</build>
```
how can I run this test?

**Comment by zhengchunxi** [comment]
oh, I forgot to add phantomjs 
```
<plugin>
				<groupId>com.github.searls</groupId>
				<artifactId>jasmine-maven-plugin</artifactId>
				<version>2.2</version>
				<executions>
					<execution>
						<configuration>
						    <jsSrcDir>src/main/webapp/javascript</jsSrcDir>
						    <jsTestSrcDir>src/main/webapp/javascript-test</jsTestSrcDir>
							<webDriverCapabilities>
								<webDriverCapability>
									<name>phantomjs.binary.path</name>
									<value>phantomjs</value>
								</webDriverCapability>
							</webDriverCapabilities>
						</configuration>
						<goals>
							<goal>test</goal>
						</goals>
					</execution>
				</executions>
			</plugin>
```
it works!
