### ISSUE TITLE
antlr error

### ISSUE THREAD

**Issue by alexpetlenko** [searls/jasmine-maven-plugin#314]
Hi there,

Firstly thanks for sharing your plugin, it appears to be highly useful for getting Jasmine unit tests into a CI environment. I'm using the following config:

```
            <plugin>
                <groupId>com.github.searls</groupId>
                <artifactId>jasmine-maven-plugin</artifactId>
                <version>2.1</version>
                <executions>
                    <execution>
                        <goals>
                            <goal>test</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
```

However I am getting a strange error when running mvn jasmine:test

```
java.lang.NoClassDefFoundError: org/antlr/runtime/RecognitionException
	at org.stringtemplate.v4.ST.<init>(ST.java:167)
	at com.github.searls.jasmine.runner.AbstractSpecRunnerHtmlGenerator.resolveHtmlTemplate(AbstractSpecRunnerHtmlGenerator.java:32)
	at com.github.searls.jasmine.runner.DefaultSpecRunnerHtmlGenerator.generateHtml(DefaultSpecRunnerHtmlGenerator.java:43)
	at com.github.searls.jasmine.runner.DefaultSpecRunnerHtmlGenerator.generate(DefaultSpecRunnerHtmlGenerator.java:22)
	at com.github.searls.jasmine.runner.CreatesRunner.create(CreatesRunner.java:48)
	at com.github.searls.jasmine.server.JasmineResourceHandler.createSpecRunnerIfNecessary(JasmineResourceHandler.java:50)
	at com.github.searls.jasmine.server.JasmineResourceHandler.handle(JasmineResourceHandler.java:37)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1088)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1024)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:135)
	at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:255)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:116)
	at org.eclipse.jetty.server.Server.handle(Server.java:370)
	at org.eclipse.jetty.server.AbstractHttpConnection.handleRequest(AbstractHttpConnection.java:494)
	at org.eclipse.jetty.server.AbstractHttpConnection.headerComplete(AbstractHttpConnection.java:971)
	at org.eclipse.jetty.server.AbstractHttpConnection$RequestHandler.headerComplete(AbstractHttpConnection.java:1033)
	at org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:640)
	at org.eclipse.jetty.http.HttpParser.parseAvailable(HttpParser.java:231)
	at org.eclipse.jetty.server.AsyncHttpConnection.handle(AsyncHttpConnection.java:82)
	at org.eclipse.jetty.io.nio.SelectChannelEndPoint.handle(SelectChannelEndPoint.java:696)
	at org.eclipse.jetty.io.nio.SelectChannelEndPoint$1.run(SelectChannelEndPoint.java:53)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:608)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:543)
	at java.lang.Thread.run(Thread.java:745)
```

If I run mvn jasmine:bdd I get a similar issue and the jetty returns a 500.
Any help highly appreciated!

**Comment by alexpetlenko** [comment]
Update: This config seems to have fixed the issue, I guess there may have been a dependency clash with another version of antlr in my pom.

         ```
   <plugin>
                <groupId>com.github.searls</groupId>
                <artifactId>jasmine-maven-plugin</artifactId>
                <version>2.2</version>
                <dependencies>
                    <dependency>
                        <groupId>org.antlr</groupId>
                        <artifactId>antlr4</artifactId>
                        <version>4.5.3</version>
                    </dependency>
                </dependencies>
                <executions>
                    <execution>
                        <goals>
                            <goal>test</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
```
